[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg add-config dpos.feeFloor --build 0 --vote-threshold 75 -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "excludes"
  Expected = ['Error']
  
[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg get-config dpos.feeFloor"
  Condition = "contains"
  Expected = ['dpos.feeFloor', 'VOTING']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-config dpos.feeFloor --value 70 -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-config dpos.feeFloor --value 70 -k {{index $.NodePrivKeyPathList 2}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-config dpos.feeFloor --value 70 -k {{index $.NodePrivKeyPathList 3}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  Delay = 5000
  RunCmd = "{{ $.LoomPath }} chain-cfg get-config dpos.feeFloor"
  Condition = "contains"
  Expected = ['dpos.feeFloor', 'ACTIVATED']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg config-value dpos.feeFloor"
  Condition = "contains"
  Expected = ['dpos.feeFloor', '70']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-config dpos.feeFloor --value 66 -k {{index $.NodePrivKeyPathList 3}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-config dpos.feeFloor --value 66 -k {{index $.NodePrivKeyPathList 2}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg get-config dpos.feeFloor"
  Condition = "contains"
  Expected = ['dpos.feeFloor', 'VOTING', '50']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg set-config dpos.feeFloor --value 66 -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  Delay = 5000
  RunCmd = "{{ $.LoomPath }} chain-cfg get-config dpos.feeFloor"
  Condition = "contains"
  Expected = ['dpos.feeFloor', 'ACTIVATED']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg config-value dpos.feeFloor"
  Condition = "contains"
  Expected = ['dpos.feeFloor', '66']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg remove-config dpos.feeFloor -k {{index $.NodePrivKeyPathList 1}}"
  Condition = "contains"
  Expected = ['[ChainConfig] not authorized']

[[TestCases]]
  RunCmd = "{{ $.LoomPath }} chain-cfg remove-config dpos.feeFloor -k {{index $.NodePrivKeyPathList 0}}"
  Condition = "contains"
  Expected = ['']

[[TestCases]]
  Delay = 1000
  RunCmd = "{{ $.LoomPath }} chain-cfg config-value dpos.feeFloor"
  Condition = "excludes"
  Expected = ['66']

